### ISSUE TITLE
predict_proba option for Estimator

### ISSUE THREAD

**Issue by agamemnonc** [axopy/axopy#64]
Similar to #61, it might be useful to have a `return_proba` kwarg in `Estimator` for cases where the user needs the prediction probabilities rather than predicted class.

@ixjlyons do you think this would be useful at all?

If so, I am happy to submit a PR.

**Comment by ixjlyons** [comment]
Sounds good to me. Possibly also `predict_log_proba`? Then there's a question of an API for supporting all three `predict` methods. I think it's often just `log(predict_proba(X))` which could be implemented with an extra `Callable(lambda x: np.log(x))` block, but that may not always be the case (the naive Bayes classifiers for example use `predict_log_proba` as the main computational method and use `np.exp(self.predict_log_proba(X))`).

I guess I'm fine with `return_proba` *and* `return_log_proba` keyword args which default to `False` and just check that both aren't `True`. It may also be a good idea to check `if hasattr(estimator, 'predict_proba')` in `__init__` to help catch problems during pipeline construction rather than later on when you've gone through the trouble of fitting it and go to call `process`. The error checking throughout AxoPy is bad but no better time to start improving than now :)
