### ISSUE TITLE
Issue with QApplication

### ISSUE THREAD

**Issue by agamemnonc** [axopy/axopy#77]
I am using some DAQ-specific software which communicates with the hardware using Qt. 

This results in an issue the first time that `get_qtapp()` is called in the following line
https://github.com/axopy/axopy/blob/39945b5dc5bc0ebea1a42ec95f3d9e64451c0a8a/axopy/gui/main.py#L131
because a `QApplication` already exists and therefore a new one is not created. 

The program crashes with the following error:
```
QWidget: Cannot create a QWidget without QApplication
```

(Apologies I can't provide code to reproduce the error without using the hardware I am using). 

The trivial way to address this problem is to call `get_qtapp()` before the device instance is constructed, so that it is `axopy` that creates the `QApplication`. But I was wondering if there might be a more elegant way of handling this case? 

@ixjlyons  Please feel free to close if you think this is not worth the effort.

**Comment by ixjlyons** [comment]
Interesting. So to make sure I understand: you have a script that in some way launches a Qt application to work with a DAQ then when you try to run an experiment in that script it fails? I'm not actually sure why that would cause a problem, but I can try to work on a reproducible example. I think there are generally some improvements to be made regarding how AxoPy handles the application instance (e.g. #55), so I'd like to look more into this anyway.

One thought: is the DAQ application using a `QMainWindow`? I don't think you can have more than one per application but I'd imagine that would produce a different error.

**Comment by agamemnonc** [comment]
> Interesting. So to make sure I understand: you have a script that in some way launches a Qt application to work with a DAQ then when you try to run an experiment in that script it fails?

Yes, that's almost right, except that I don't have another script running. Rather, when the device instance is created (in order to pass it in the Experiment), a Qt application is launched in the background.

> One thought: is the DAQ application using a `QMainWindow`?

I am afraid I have very little knowledge of what's happening under the hood, as the library (link [here](https://github.com/dashesy/CereLink)) is actually written in C++ (and compiled) and I am only using the Python wrapper. Sorry I couldn't be of any more help!

**Comment by ixjlyons** [comment]
[This](https://github.com/dashesy/CereLink/blob/master/cbmex/cbsdk.cpp#L818-L819) seems to be the culprit. Example:

```python
import axopy
from PyQt5 import QtCore, QtWidgets

app2 = QtCore.QCoreApplication([])
#app2 = QtWidgets.QApplication([])

axopy.experiment.Experiment(
    daq=axopy.daq.NoiseGenerator(),
    subject='test',
    allow_overwrite=True
).run(axopy.task.Oscilloscope())
```

`QApplication.instance()` (i.e. in `get_qtapp()`) will return any application instance inheriting from `QCoreApplication`, so the Cerelink SDK's `QCoreApplication` is returned and used. The error is indicating you can't use widgets (from `QtWidgets`) with a `QCoreApplication` (it has an event loop but no GUI). The solution of using `get_qtapp()` first means the SDK won't create a new application and will use AxoPy's. I don't know if this will cause problems with the DAQ, but if not, that's the workaround I'd recommend for now.

One idea I had was to add a check specifically for `QApplication` to make sure a new instance is created even if there's a `QCoreApplication` already, but it doesn't seem to work. I believe this is because there should only ever be one application instance per process.

```python
    inst = QtWidgets.QApplication.instance()
    if inst is None or not isinstance(inst, QtWidgets.QApplication):
        qtapp = QtWidgets.QApplication(sys.argv)
    else:
        qtapp = inst
```

The only other thing I can think of would be to call `get_qtapp` automatically on import of the `gui`  module, but I don't particularly like import side effects like that, especially now that `import axopy` goes ahead and imports all the submodules. If you want to just use the `storage` module for post-processing some data, for example, it doesn't really make sense to create an application instance.

**Comment by agamemnonc** [comment]
Well spotted, thanks!
